modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="iradeseus3d"
version="1.0.0"
displayName="IRA-DE-SEUS-3D"
authors="IGY_gaming"
description='''
Ritual mitologico 3D masivo: Zeus convoca la ira de varios dioses mediante
modelos 3D, rayos, sigilos, proyectiles divinos, daño por fases y crater final.
'''

[[dependencies.iradeseus3d]]
modId="forge"
mandatory=true
versionRange="[47.3.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.iradeseus3d]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
